
import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";


const Home: NextPage = () => {
  return (
    <div
      className="container"
    >
      <Head>
        <title>Agency app</title>
        <meta name="descrption" content="Generated by next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="w-[100vw] h-[100vh] flex flex-col justify-center items-center">

        <div className="font-bold text-9xl">Himanish</div>
      </div>
      <footer className="row-start-3 flex gap-[24px] flex-wrap items-center justify-center">

      </footer>
    </div>
  );
}
export default Home
