
import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import AgencyHead from "../components/webHead";
import Aboutus from "../components/aboutus";

const Home: NextPage = () => {
  return (
    <div
      className="w-[100vw]"
    >
      <Head>
        <title>Agency app</title>
        <meta name="descrption" content="Generated by next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AgencyHead />
      <Aboutus />



      <footer className="">

      </footer>
    </div>
  );
}
export default Home
